### PR TITLE
Add HDF5 and PDC projects

### PR DESCRIPTION
**Pull request by qkoziol**
Hopefully, I got the Markdown correct. :-)

### CODE REVIEW

**Comment by carlosmalt** [comment]
Can you move these projects into the SkyhookDM part, please?

**Comment by qkoziol** [comment]
Do they belong in the SkyhookDM section?  Some of them are not very closely related.

**Comment by carlosmalt** [comment]
That's OK -- For this summer we are structuring project ideas around fellows. So any up-votes for @jlefevre would benefit you as well.

**Comment by qkoziol** [comment]
OK, I'll revise.

**Comment by qkoziol** [comment]
How's that look?

**Pull request merged**
